---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: rust

inputs:
- name: rust-project

run:
  path: sh
  args:
  - -exc
  - |
    cd rust-project
    make build
outputs:
- name: build-output
